import { getConfig } from '@/config';

/**
 * The origin a card's URL should use for *this* request.
 *
 * A card carries an absolute URL — it is printed on paper and scanned by a phone that has never
 * seen this server — so `PUBLIC_CARD_ORIGIN` is the real answer and it wins whenever it is set to
 * something a phone can reach.
 *
 * A **loopback** origin is a development default, though: a card generated by a dashboard on
 * `http://localhost:3200` carries a URL that only resolves on the machine that served it. His
 * complaint (2026-10-01) was exactly that — the card link in the dashboard went nowhere, because
 * he was looking at the LAN address and the link said `localhost`. So for loopback configurations
 * the request is believed instead, including the `X-Forwarded-*` headers a proxy in front would
 * set, and a QR code scanned by a phone on the same network works.
 */
const LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '[::1]', '::1']);

function isLoopback(origin: string): boolean {
  try {
    return LOOPBACK_HOSTS.has(new URL(origin).hostname);
  } catch {
    return false;
  }
}

export function cardOrigin(request: Request, configured = getConfig().PUBLIC_CARD_ORIGIN): string {
  if (!isLoopback(configured)) return configured.replace(/\/$/, '');

  const url = new URL(request.url);
  const host = request.headers.get('x-forwarded-host') ?? request.headers.get('host') ?? url.host;
  const protocol = request.headers.get('x-forwarded-proto') ?? url.protocol.replace(':', '');
  return `${protocol}://${host}`;
}
