import { describe, expect, it } from 'vitest';
import { cardOrigin } from '@/lib/card-origin';

/**
 * Which address a card's URL carries.
 *
 * A card is printed with an absolute URL, so a configured origin wins whenever a phone can reach
 * it. A loopback origin is a development default, and a card printed from it carries an address
 * that only resolves on the machine that served it, so there the request is believed instead.
 * Both halves matter: the dashboard link doing nothing from another device is the bug this exists
 * for, and a real domain silently being replaced by an internal host would be a worse one.
 */
const request = (host: string, headers: Record<string, string> = {}, protocol = 'http') =>
  new Request(`${protocol}://${host}/dashboard/card/card.jpg`, { headers: { host, ...headers } });

describe('cardOrigin', () => {
  it('keeps a configured origin that a phone can actually reach', () => {
    expect(cardOrigin(request('internal.local', { host: 'internal.local' }, 'https'), 'https://noka.care')).toBe(
      'https://noka.care',
    );
  });

  it('believes the request when the configuration is loopback', () => {
    // The card is generated by a dashboard on the LAN; the URL has to be one the phone can open.
    expect(cardOrigin(request('10.10.10.20:3200', { host: '10.10.10.20:3200' }), 'http://localhost:3200')).toBe(
      'http://10.10.10.20:3200',
    );
  });

  it('uses the forwarded host and protocol when a proxy is in front', () => {
    expect(
      cardOrigin(
        request('127.0.0.1:3200', {
          host: '127.0.0.1:3200',
          'x-forwarded-host': 'noka.example',
          'x-forwarded-proto': 'https',
        }),
        'http://localhost:3200',
      ),
    ).toBe('https://noka.example');
  });

  it('strips a trailing slash so the URL never doubles it', () => {
    expect(cardOrigin(request('noka.care', {}, 'https'), 'https://noka.care/')).toBe('https://noka.care');
  });

  it('treats an unparsable configuration as one to keep, not one to replace', () => {
    // Better a wrong-looking configured value than silently rewriting somebody's production origin.
    expect(cardOrigin(request('internal.local'), 'not a url')).toBe('not a url');
  });
});
